security:
    encoders:
        Tec\Ayt\CoreBundle\Entity\Admin:
            algorithm:          sha1
            encode_as_base64:   false
            iterations:         1

        Tec\Ayt\CoreBundle\Entity\User:
                    algorithm:          sha1
                    encode_as_base64:   false
                    iterations:         1

    providers:
            main:
                entity:
                    class:  Tec\Ayt\CoreBundle\Entity\User
                    property: username

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN
        ROLE_SYSTEM_ADMIN:  ROLE_SUPER_ADMIN


    firewalls:
        dev:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            security:   false
        login_firewall:
            pattern:    ^/login$
            security:   false
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login/check
                default_target_path: /success
            logout:
                path:   /logout
                target: /

    access_control:
        # ROLE_SYSTEM_ADMIN
        # ROLE_SUPER_ADMIN
        # ROLE_ADMIN
        # ROLE_USER
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }